### Bibliotecas

In [1]:
import numpy as np

In [2]:
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

In [3]:
[[i + 1 for i in row] for row in matrix]

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

In [4]:
# Construir um array com uma lista simples resulta em um array 1d
array1 = np.array([10, 100, 1000.])

# Construir um array com uma lista aninhada resulta em um array 2d
array2 = np.array([[1., 2., 3.],
                   [4., 5., 6.]])

In [5]:
array1.dtype

dtype('float64')

In [6]:
float(array1[0])

10.0

#### Vetorização e Transmissão

In [7]:
array2 + 1

array([[2., 3., 4.],
       [5., 6., 7.]])

In [8]:
array2 * array2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [9]:
print(array1 * array2)
print(array2 * array1)

[[  10.  200. 3000.]
 [  40.  500. 6000.]]
[[  10.  200. 3000.]
 [  40.  500. 6000.]]


In [10]:
array2 @ array2.T # array2.T é um atalho para array2.transpose()

array([[14., 32.],
       [32., 77.]])

In [11]:
# Funções Universais (ufunc)
np.sqrt(array2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [12]:
array2.sum(axis= 0) # Retorna um array 1d

array([5., 7., 9.])

In [13]:
array2.sum()

np.float64(21.0)

#### Criando e Manipulando arrays

In [14]:
print(array1[2], "\n")        # Retorna um escalar
print(array2[0 , 0], "\n")    # Retorna um escalar
print(array2[: , 1:], "\n")   # Retorna um array 2d
print(array2[: , 1], "\n")    # Retorna um array 1d
print(array2[1 , :2], "\n")   # Retorna um array 1d

1000.0 

1.0 

[[2. 3.]
 [5. 6.]] 

[2. 5.] 

[4. 5.] 



#### Construtores de Array Úteis

In [18]:
np.arange(2 * 5).reshape(2, 5) # 2 linhas, 5 colunas

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
np.random.randn(2, 3) # 2 linhas, 3 colunas

array([[-0.80326719, -0.44145477,  0.51428598],
       [-0.32935772,  0.6507933 , -0.67782497]])

#### Visualizar vs Copiar

In [20]:
array2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [22]:
subset = array2[: , :2]
subset

array([[1., 2.],
       [4., 5.]])

In [25]:
subset[0, 0] = 1000
subset

array([[1000.,    2.],
       [   4.,    5.]])

In [26]:
subset = array2[: , :2].copy()